#!/bin/bash

#### Mac OS X specifc Bash settings ###

echo "Loading Mac OS X specific settings"

#export PATH="/usr/local/bin:/usr/local/mysql/bin:$PATH"
#export PATH=/usr/local/mysql/bin:/Applications/MAMP/bin/php5/bin:$PATH:/Users/Jonix/Projects/Work/TopSecret/Mapiton/Native/Pigsty/MacOSX:/Users/Jonix/Scripts:

export PATH=/Applications/Emacs.app/Contents/MacOS/:/opt/subversion/bin:Applications/MAMP/Library/bin:/Applications/MAMP/bin/php5/bin:/Users/Jonix/Scripts:/Users/Jonix/Scripts/GitScripts:/Users/Jonix/Projects/Work/Mapiton/Native/Pigsty/MacOSX:/usr/texbin/latex:$PATH:


export MANPATH="/usr/local/man:$MANPATH"

export EDITOR="/usr/bin/mate --wait --change-dir"
